### ISSUE TITLE
Suggestion: Distribute binaries as a "release" archive rather than in git

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/iosevka-comfy#11]
Hi Prot,

Have you considered distributing the built fonts from a "GitHub Release" as an archive rather than adding the built files to git?  It could substantially reduce the size of the git repo, for one thing.  Also, it could likely be automated through GitHub Actions, which would save you from having to upload the built files at all.

Just an idea, in case you hadn't considered it yet.  :)

Thanks for your work!

Adam

**Comment by protesilaos** [comment]
> From: Adam Porter ***@***.***>
> Date: Tue,  5 Dec 2023 20:14:23 -0800
>
> Hi Prot,

Hello Adam,

> Have you considered distributing the built fonts from a "GitHub
> Release" as an archive rather than adding the built files to git? It
> could substantially reduce the size of the git repo, for one thing.
> Also, it could likely be automated through GitHub Actions, which would
> save you from having to upload the built files at all.
>
> Just an idea, in case you hadn't considered it yet.  :)

It's a good idea! I have not done any of this before, so I need to learn
how. The practical problem, however, is that this is GitHub-specific and
will not work with the default SourceHut repo.

I took a brief look into Git Large File Storage and it seems relevant to
my case here. But, again, it needs research and I have not had time for
it.

If you have ideas/patches, I am happy to incorporate them. I don't like
the current state of the massive git repo and want to make things easier
for everyone.

> Thanks for your work!

You are welcome!

All the best,
Prot

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I decided to opt for Git LFS. Hopefully it all goes well and the repo is easier to manage.

**Comment by protesilaos** [comment]
As I am pushing the changes now, I notice that Git LFS does not work the way I assumed. I will need to review things.
