### ISSUE TITLE
Comparison screenshots

### ISSUE THREAD

**Issue by leinfink** [protesilaos/iosevka-comfy#14]
It would help to have some screenshots comparing standard Iosevka and Iosevka-Comfy. Just by reading the text, it's hard to understand how the differences would look.

**Comment by protesilaos** [comment]
> From: Henrik ***@***.***>
> Date: Sat,  6 Jul 2024 11:19:19 -0700
>
> It would help to have some screenshots comparing standard Iosevka and
> Iosevka-Comfy. Just by reading the text, it's hard to understand how
> the differences would look.

The problem with this is that Iosevka has a new version quite frequently
and then those screenshots may become out-of-date. I think it is easier
to install both and try them side-by-side.

-- 
Protesilaos Stavrou
https://protesilaos.com
