### ISSUE TITLE
HORIZONTAL ELLIPSIS displays wider than space

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/iosevka-comfy#15]
Hi Prot,

I noticed that, when using this font, the Unicode character U+2026 "HORIZONTAL ELLIPSIS" displays with a width that's wider than the space character.  When using the function/variable `truncate-string-ellipsis` to truncate strings for alignment (e.g. using `taxy-magit-section` columns), and using that character as the ellipsis string, it causes visual alignment to break.

I don't know how feasible it would be to fix this (assuming it's agreed to be a flaw), but it would be nice.  :)

Thanks for your work on this font.  I've been using it as my default for a few months now, and I'm enjoying it.

**Comment by protesilaos** [comment]
> From: Adam Porter ***@***.***>
> Date: Sun, 18 Aug 2024 17:15:35 -0700
>
> Hi Prot,

Hello Adam,

> I noticed that, when using this font, the Unicode character U+2026
> "HORIZONTAL ELLIPSIS" displays with a width that's wider than the
> space character. When using the function/variable
> `truncate-string-ellipsis` to truncate strings for alignment (e.g.
> using `taxy-magit-section` columns), and using that character as the
> ellipsis string, it causes visual alignment to break.

Thank you for telling me this!

> I don't know how feasible it would be to fix this (assuming it's
> agreed to be a flaw), but it would be nice. :)

I am in the process of rebuilding the font on top of the latest Iosevka.
This will take a while for me to test everything, but I should be done
in a few days.

> Thanks for your work on this font. I've been using it as my default
> for a few months now, and I'm enjoying it.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I am now pushing the new version. It will take some time. If upstream Iosevka had fixed this character, then you will be fine. Otherwise, there is nothing I can do.

**Comment by alphapapa** [comment]
Hi Prot,

Upon further investigation, I found this comment on the Iosevka repo: https://github.com/be5invis/Iosevka/issues/1121#issuecomment-860363499  It explains that the Iosevka Term subfamilies have that character at the one-space width.

Would it be possible to adjust the Iosevka Comfy specification for that character to match its width in Iosevka Term?

**Comment by protesilaos** [comment]
Oh, I see. Then you need the "fixed" variants, which are all monospaced. The other ones support some naturally wide characters like the em dash and ligatures.

Here is the demo:

![Screenshot_2024-08-23_10-02-32](https://github.com/user-attachments/assets/8c7c1d13-1205-4d04-88ae-b6e7d637b72c)

![Screenshot_2024-08-23_10-02-40](https://github.com/user-attachments/assets/1d2eef4f-4a26-40e5-9a54-70873abca91c)

**Comment by alphapapa** [comment]
Ah, I'm sorry, I didn't read the documentation carefully enough to understand those distinctions.  (I confess to feeling a bit overwhelmed with the number of variations the Iosevka family offers.)  I guess I just need to use that instead.  Thank you, Prot, for patiently explaining this to me.  (As often as I am on the other side of users who overlook info in the docs, I shouldn't make the same mistake myself.)

**Comment by protesilaos** [comment]
> From: Adam Porter ***@***.***>
> Date: Fri, 23 Aug 2024 02:17:57 -0700
>
> Ah, I'm sorry, I didn't read the documentation carefully enough to
> understand those distinctions. (I confess to feeling a bit overwhelmed
> with the number of variations the Iosevka family offers.) I guess I
> just need to use that instead. Thank you, Prot, for patiently
> explaining this to me. (As often as I am on the other side of users
> who overlook info in the docs, I shouldn't make the same mistake
> myself.)

That's fine, no worries! I am happy to help.

-- 
Protesilaos Stavrou
https://protesilaos.com
