### ISSUE TITLE
repeated sub-folders under main folder iosevka-comfy-duo

### ISSUE THREAD

**Issue by umbrellaid** [protesilaos/iosevka-comfy#16]
Hi Prot, Thank you for your hard work on these fonts. In the folder "iosevka-comfy-motion-fixed" there are two sub-folders under this folder "iosevka-comfy-duo" and "iosevka-comfy-motion-duo". I believe this may be a mistake. None of the other folders have sub-folders like this, unless there is some other reason for the folders to be repeated. Thank you, take care and have a nice day. Kind regards.

**Comment by protesilaos** [comment]
> From: umbrellaid ***@***.***>
> Date: Sun, 25 Aug 2024 11:05:41 -0700
>
> Hi Prot, Thank you for your hard work on these fonts. In the folder
> "iosevka-comfy-motion-fixed" there are two sub-folders under this
> folder "iosevka-comfy-duo" and "iosevka-comfy-motion-duo". I believe
> this may be a mistake. None of the other folders have sub-folders like
> this, unless there is some other reason for the folders to be
> repeated. Thank you, take care and have a nice day. Kind regards.

Thank you! It is a mistake, indeed. I will remove them now.

-- 
Protesilaos Stavrou
https://protesilaos.com
