### ISSUE TITLE
Missing tag for latest release

### ISSUE THREAD

**Issue by DamienCassou** [protesilaos/iosevka-comfy#19]
Could you please add a git tag for 2.1.0? This helps packagers.

**Comment by protesilaos** [comment]
> From: Damien Cassou ***@***.***>
> Date: Sun, 20 Oct 2024 12:53:51 -0700
>
> Could you please add a git tag for 2.1.0? This helps packagers.

Thank you! I just pushed it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by DamienCassou** [comment]
Thank you!
