### ISSUE TITLE
The a and the o are very similar 

### ISSUE THREAD

**Issue by DamienCassou** [protesilaos/iosevka-comfy#2]
I can hardly distinguish the a and the o in your version of Iosevka.

# Default Iosevka
![2022-07-21-150613](https://user-images.githubusercontent.com/217543/180220924-192c3c47-a258-4013-a94b-88f87ed2db62.png)

# Iosevka Comfy
![2022-07-21-150631](https://user-images.githubusercontent.com/217543/180220929-8f5ce88c-5e64-4d14-a2a0-5f9e888f5ab8.png)

**Comment by protesilaos** [comment]
Hello @DamienCassou!

I see.  Let me check how best to resolve this and I will report back to you.

**Comment by protesilaos** [comment]
I had to also change `b`, `d`, and `u`.  What do you think?

![Screenshot from 2022-07-21 18-21-18](https://user-images.githubusercontent.com/12828033/180251515-dbddcdaa-ab0b-4ce4-b781-3a6212b34e49.png)

![Screenshot from 2022-07-21 18-21-33](https://user-images.githubusercontent.com/12828033/180251521-e441df24-80c5-427b-9eae-abe96c3b2ff8.png)

![Screenshot from 2022-07-21 18-11-14](https://user-images.githubusercontent.com/12828033/180250392-80f71b8f-4571-400b-b8c9-c5d2c97ad7f0.png)

![Screenshot from 2022-07-21 18-11-22](https://user-images.githubusercontent.com/12828033/180250401-7fdbd554-ed48-492c-816e-6d7d477c401c.png)

**Comment by DamienCassou** [comment]
This looks perfect, thank you very much.

Out of curiosity, why did you have to change other letters?

**Comment by protesilaos** [comment]
> This looks perfect, thank you very much.

Very well!  I will push the change in a few minutes.  Need to update the docs first and prepare a changelog.

> Out of curiosity, why did you have to change other letters?

I was thinking about it already.  The reason is that they were not consistent with the rounded style.  You can now see the lower part of the `a`, `b`, `d`, `u` how it has the same curve.  Before the `a` and `u` had a tail, while the others had a straight line at the bottom.

**Comment by protesilaos** [comment]
Just published the new version.  Please check.

**Comment by DamienCassou** [comment]
> Just published the new version. Please check.

This is perfect. Thank you very much.

**Comment by protesilaos** [comment]
You're welcome!
