### ISSUE TITLE
nerd fonts

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/iosevka-comfy#6]
hi prot. does this work out of the box with nerd fonts and the emacs nerd-font packages?

**Comment by protesilaos** [comment]
The Emacs packages should work just fine: you actually install separate font files for them.

Otherwise I don't know what the expectation is with nerd fonts.  I never used them in earnest.

If you try this, please let me know how it goes.

**Comment by gitrj95** [comment]
seems to work just fine
