### ISSUE TITLE
Japanese signs are bigger than letters

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/iosevka-comfy#7]
Hej prot,

let me preface with a thank you for making a font I consider really gorgeous and building so much relevant stuff for me (and others) to use.

Now, in denote, I have a kind of knowledge archive which I build when reading newspaper articles and recently decided that it should be using not only the western written representation but also its "native" representation.

I thus noticed that, in a denote dired buffer, using japanese signs results in a bigger gap between two entries than would be the case with letters like "a" or "c".

For comparison, here are some of the notes I produced today.
```
20230710T074546--asics__gebilde_unternehmen.org
20230710T070814--asia-society__gebilde_ngo.org
20230710T064551--自由民主党-liberaldemokratische-partei-ldp__gebilde_partei.org
20230710T074818--sri-lanka__land.org
```
I would expect -- as is the case over here -- that the gap between the entry stay the same regardless of the language and according signs used. Since I have started incorporating native language signs only today, I can't judge if the same is true for other languages, though I vaguely remember to have had a similar irritation when first using arabic signs.

Is there something to be done about this, or is it a conscious design decision?

Have a good day :-)

**Comment by protesilaos** [comment]
Hello @hapst3r!

I have noticed this before.  I believe it is a general Iosevka issue, though I have not tested it.  Even when I use the "fixed" variants, the glyphs are wider.

**Comment by hapst3r** [comment]
Hi @protesilaos

Yes, it is the case no matter which variant I use.

So, what you are suggesting is asking "upstream" about the issue?

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Sun, 23 Jul 2023 07:00:43 -0700
>
> Hi @protesilaos
>
> Yes, it is the case no matter which variant I use.
>
> So, what you are suggesting is asking "upstream" about the issue?

Yes, I think this is worth asking there since I am not doing anything to
affect Japanese signs.

-- 
Protesilaos Stavrou
https://protesilaos.com
