### ISSUE TITLE
Lacking medium weight

### ISSUE THREAD

**Issue by madjxatw** [protesilaos/iosevka-comfy#8]
The regular weight looks too thin in terminals on Linux, it would be great if the medium weight gets packaged!

**Comment by protesilaos** [comment]
> From: madjxatw ***@***.***>
> Date: Sat,  2 Sep 2023 09:12:56 -0700
>
> The regular weight looks too thin in terminals on Linux, could you
> please get the medium weight packaged?

In principle, yes.  Though I have a metered Internet connection right
now, so I will need to do this towards the end of the month.

Do you know which weight counts as "medium"?  The "regular" is 400.
Perhaps "medium" is 500?  And then we may also include "semibold" at
600?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by madjxatw** [comment]
Thanks @protesilaos!
regular (400), medium (500), semibold (600), bold (700).

**Comment by protesilaos** [comment]
I just pushed the changes.  Thank you for your patience.  This takes a lot of time to do, due to the computationally expensive procedure to build the fonts.

**Comment by madjxatw** [comment]
Cheers! I've tried the new release, the medium weight looks perfect. Greatly appreciate your contribution!

**Comment by protesilaos** [comment]
> From: madjxatw ***@***.***>
> Date: Wed,  4 Oct 2023 22:06:13 -0700
>
> Cheers! I've tried the new release, the medium weight looks
> perfect. Greatly appreciate your contribution!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
